<?php
    /**
     * school
     *
     * @copyright Copyright © 2018 Kinspeed Ltd. All rights reserved.
     * @author    luke.paoloni@kinspeed.com
     */
?>
<a href="<?php echo $this->getLinkedCategoryUrl(); ?>">
    <?php echo $this->getLinkedCategoryUrl(); ?>
</a>
<?php //$collection = $this->getTabUrl(); ?>
<!--<pre>-->
<!--    --><?php //print_r($collection->getId()); ?>
<!--</pre>-->