/*
SQLyog Community
MySQL - 10.1.31-MariaDB : Database - school_trends_mg2
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `kinspeed_schools_school_suppliers` */

DROP TABLE IF EXISTS `kinspeed_schools_school_suppliers`;

CREATE TABLE `kinspeed_schools_school_suppliers` (
  `entity_id` int(10) unsigned NOT NULL COMMENT 'School Supplier ID',
  `supplier_name` text NOT NULL COMMENT 'School Supplier Name',
  PRIMARY KEY (`entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='School Suppliers';

/*Data for the table `kinspeed_schools_school_suppliers` */

insert  into `kinspeed_schools_school_suppliers`(`entity_id`,`supplier_name`) values 
(1,'School Trends'),
(2,'Price & Buckland'),
(3,'Your School Uniform'),
(4,'Mapac'),
(5,'PMG'),
(6,'Border Embroideries'),
(7,'Henry Smith'),
(8,'Initially Yours'),
(9,'Emblem'),
(10,'Leonard Hudson'),
(11,'Casual Schoolwear'),
(12,'Classwear'),
(13,'Direct Schoolwear'),
(14,'National Schoolwear Centre'),
(15,'Unismart'),
(16,'Yourlogohere.com'),
(17,'Tesco'),
(18,'Marks & Spencer'),
(19,'Smartypants'),
(20,'Teenywear'),
(21,'Cladish Sports'),
(22,'Sanco'),
(23,'My School Direct'),
(24,'Stevensons/Len Smith'),
(25,'Schooldays'),
(26,'local shop'),
(27,'Goodies'),
(28,'Example Uniform'),
(29,'Kidzone'),
(30,'Lester Bowden'),
(31,'School Office'),
(32,'Doesnt State'),
(33,'Brigade'),
(34,'Schoolwear Centre'),
(36,'Strands Schoolwear'),
(37,'Hewits'),
(38,'Sport International'),
(39,'Zeco'),
(40,'Oz Schoolwear'),
(41,'Your Schoolwear'),
(42,'Designer School Uniforms'),
(43,'Graduates'),
(44,'DSU'),
(45,'Simmonds'),
(46,'Broadbridges'),
(47,'John Lewis'),
(48,'Paul Marchant'),
(49,'School Togs'),
(50,'Horncastles'),
(51,'Bookbag.com'),
(52,'Boffins'),
(53,'Simply Schoolwear'),
(54,'Super Stitch'),
(55,'Schoolcolours'),
(56,'Uniforms 2 U'),
(57,'Bromley Schoolwear'),
(58,'One to One'),
(59,'In-School Shop'),
(60,'Broadwater Sports'),
(61,'Rogerson & Crew'),
(62,'TFS'),
(63,'Ex Ernest Newson'),
(64,'Philip Mann'),
(65,'JB Sports Shop'),
(66,'Twin Set Shop'),
(67,'Sewing Shop'),
(68,'Longfield Wools Shop'),
(69,'Whitehall Clothiers'),
(70,'Jays Sports Shop'),
(71,'Mathews Shop'),
(72,'Caseys Shop'),
(73,'Uniform Direct'),
(74,'Stitch Designs'),
(75,'Schoolwear Inc.'),
(76,'Online School Uniform'),
(77,'Prit Uniforms'),
(78,'Wovina'),
(79,'Andrew Hyde'),
(80,'School Uniform 24/7'),
(81,'Uniform Leisurewear'),
(82,'Band Box'),
(83,'Sussex Uniforms'),
(84,'Trutex'),
(85,'Uniform Base'),
(86,'Unismart'),
(87,'Kathryn Billings'),
(88,'Schoolwear For Less'),
(89,'test'),
(90,'Logo Sport'),
(91,'Ricara'),
(92,'Taylor Made Uniforms'),
(93,'Heber'),
(94,'Term Time'),
(95,'Dexter & Gordon'),
(96,'Non Uniform School'),
(97,'Other unknown'),
(98,'X Schoolwear For Less'),
(99,'Scholars'),
(100,'School Uniform Direct'),
(101,'Just Schoolwear'),
(102,'Clive Marks'),
(103,'Academy Suppliers'),
(104,'School Kit'),
(105,'School ID'),
(106,'Harrods'),
(107,'Workwear For Less'),
(108,'Ace'),
(109,'Active Leisurewear'),
(110,'Alstons'),
(111,'Anglia Sports'),
(112,'APC'),
(113,'Bainbridges'),
(114,'Baru'),
(115,'Begoni'),
(116,'Border Embroidery'),
(117,'Bradsports'),
(118,'Brian Shantry'),
(119,'Bristows'),
(120,'Brodwaith'),
(121,'Buxton & Bonnet'),
(122,'Carlisle Embroidery'),
(123,'Certa Cito'),
(124,'Charles Kirk'),
(125,'Clemmies'),
(126,'Cliffs of Doncaster'),
(127,'Club Sport'),
(128,'D P Leisure'),
(129,'Dancers'),
(130,'Early Years'),
(131,'Eldon School Wear'),
(132,'Elizabeths'),
(133,'Elvin Dennis'),
(134,'Emblematic'),
(135,'Ernest Newson'),
(136,'Forresters Sports, Mold'),
(137,'Fruit Of The Loom'),
(138,'Gambits'),
(139,'Gemini'),
(140,'Getit4school.com'),
(141,'Gilmours'),
(142,'Gogna'),
(143,'Grantham Clothing'),
(144,'Identity'),
(145,'Impressions'),
(146,'In Stitches'),
(147,'Innovations'),
(148,'Jean Station'),
(149,'Jerzees'),
(150,'John Matthews'),
(151,'Katherine Billings'),
(152,'Local'),
(153,'Local Market'),
(154,'Logo Express'),
(155,'Logo Leisurewear'),
(156,'Michael Hope'),
(157,'Mid Wales Embroidery'),
(158,'Moette'),
(159,'Monkhouse'),
(160,'Morleys'),
(161,'Motif Action'),
(162,'Mr Gilbert'),
(163,'National Schoolwear'),
(164,'None'),
(165,'Oakes'),
(166,'Other'),
(167,'Parent'),
(168,'Pinders'),
(169,'PMG Schoolwear'),
(170,'Rawcliffes'),
(171,'Rowlinsons'),
(172,'Scotcrest'),
(173,'Scotprint'),
(174,'Screen Stars'),
(175,'Select'),
(176,'Sign Of The Times'),
(177,'Simply Icon'),
(178,'Ski Sport'),
(179,'Skoolkit'),
(180,'Smart'),
(181,'Sportswear International'),
(182,'Stevensons'),
(183,'Stitch Design'),
(184,'Stitches Bridgnorth'),
(185,'Supermarkets i.e ASDA, Tesco..'),
(186,'Swifts'),
(187,'Tesco Direct'),
(188,'Thomas Moore'),
(189,'Top Form'),
(190,'Tots To Teams'),
(191,'Touchline'),
(192,'Trends'),
(193,'Trophy Textiles'),
(194,'Victoria Leisure'),
(195,'Victoria Manor'),
(196,'Vortex'),
(197,'Welbeck'),
(198,'Woolworths'),
(199,'Your School Uniform.com'),
(200,'Tops To Teams'),
(201,'Quantock Leisure'),
(202,'Games, Set and Match'),
(203,'Tec Promotions'),
(204,'Sportsbug shop'),
(205,'Direct4logos'),
(206,'Happy Fish'),
(207,'Penelope Anne'),
(208,'Brenda’s'),
(209,'Hargreaves Promotions'),
(211,'Salto UK');

/*Table structure for table `kinspeed_schools_school_types` */

DROP TABLE IF EXISTS `kinspeed_schools_school_types`;

CREATE TABLE `kinspeed_schools_school_types` (
  `entity_id` int(10) unsigned NOT NULL COMMENT 'School Types ID',
  `school_type` text NOT NULL COMMENT 'School Type',
  `vat_status` int(10) unsigned NOT NULL COMMENT 'VAT Status',
  PRIMARY KEY (`entity_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='School Types';

/*Data for the table `kinspeed_schools_school_types` */

insert  into `kinspeed_schools_school_types`(`entity_id`,`school_type`,`vat_status`) values 
(25,'State College',1),
(27,'State Infant & Nursery School',1),
(38,'Private Club',1),
(41,'Scout & Guide Groups',1),
(45,'State Nursery School',1),
(46,'State Playgroup',1),
(47,'State Pre-School',1),
(48,'State Kindergarten',1),
(49,'State Infants School',1),
(50,'State First School',1),
(51,'State Lower School',0),
(52,'State Combined School',0),
(53,'State Primary School',0),
(54,'State Junior School',0),
(55,'State Middle School',0),
(56,'State Grammar School',1),
(57,'State High School',1),
(58,'State Secondary School',1),
(59,'State Special Needs School',1),
(60,'State Sixth Form',1),
(61,'Private Nursery School',1),
(62,'Private Playgroup',1),
(63,'Private Pre-School',1),
(64,'Private Kindergarten',1),
(65,'Private Infants School',1),
(66,'Private First School',0),
(67,'Private Lower School',0),
(68,'Private Combined School',1),
(69,'Private Primary School',0),
(70,'Private Prep School',0),
(71,'Private Junior School',0),
(72,'Private Middle School',0),
(73,'Private Grammar School',1),
(74,'Private High School',1),
(75,'Private Secondary School',1),
(76,'PrivateSixth Form',1),
(77,'Private Dance/Stage School',1),
(78,'Private Childcare',1),
(79,'Business',1),
(80,'School Club',1),
(81,'Private College',1),
(82,'Private Pre Prep School',1),
(83,'Charity',1),
(84,'Staff',1),
(85,'State Charity Registered Special Needs School',1),
(86,'Academy Primary',0),
(87,'Nursery',1),
(89,'Primary Demo',0),
(90,'Secondary Demo',1),
(91,'Private Special Needs ',1),
(92,'Sports Club',1),
(93,'Academy Senior',1),
(94,'State Through School',1),
(95,'Special Needs Primary School',0),
(96,'School Closed',1);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
