<?php
    /** @var \Kinspeed\Schools\Block\Register\Interest $block */
    $school = $block->getSchool();
    /** @var \Kinspeed\Schools\Model\School $school */
?>
<?php if (!empty($school)) : ?>
    <form action="<?= /* @escapeNotVerified */ $block->getFormAction(); ?>" class="row" method="post">
        <input type="hidden" class="hidden" name="form_key" value="<?= $block->getFormKey(); ?>">
        <input type="hidden" class="hidden" name="school" value="<?= (int) $school->getId(); ?>">
        <div class="col-12 col-md-6">
            <div class="card">
                <?php if (!empty($school->getLogo())) : ?>
                    <img src="<?= $school->getLogo() ?>" alt="<?= $school->getSchoolName() ?> Logo" class="card-img-top" />
                <?php endif; ?>
                <div class="card-body">
                    <h3 class="card-title"><?= $school->getSchoolName(); ?></h3>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><?= $school->getAddress1() ?></li>
                    <?php if (!empty($school->getAddress2())) :?>
                        <li class="list-group-item"><?= $school->getAddress2() ?></li>
                    <?php endif; ?>
                    <?php if (!empty($school->getAddress3())) :?>
                        <li class="list-group-item"><?= $school->getAddress3() ?></li>
                    <?php endif; ?>
                    <li class="list-group-item"><?= $school->getTown() ?></li>
                    <li class="list-group-item"><?= $school->getPostcode() ?></li>
                </ul>
                <div class="card-body">
                    <button type="submit" class="btn btn-primary btn-lg">Register Interest</button>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <?php echo $block->getChildHtml( 'form_additional_info' ); ?>
            </div>
        </div>
    </form>
<?php endif; ?>
