<?php
    /*
     * schoolfinder
     *
     * @copyright Copyright © 2017 Kinspeed. All rights reserved.
     * @author    luke.paoloni@kinspeed.com
     */
?>
<?php
    /** @var \Kinspeed\Schools\Block\SchoolFinder\Search $block */
    // Add your template code here ...
?>
<?php // TODO: Need to style this in stylesheet ?>
<style>
    ul.ui-autocomplete {
        list-style-type: none;
        padding: 0 15px;
        width: 989px !important;
        background: #fff;
        box-shadow: 0px 10px 50px rgba(196, 196, 196, 0.22);
        border: 1px solid #fefefe;
        border-bottom-right-radius: 4px;
        border-bottom-left-radius:  4px;
    }

    ul.ui-autocomplete .ui-menu-item:first-of-type {
        margin-top: 15px;
    }

    .ui-autocomplete li.ui-menu-item a {
        font-size: 16px;
        cursor: pointer;
    }
</style>
<div class="floating-box card">
    <div class="card-body">
        <div class="floating-box-title py-3">
            <h2 class="page-title font-weight-bold">
                School Finder
            </h2>
        </div>
        <form action="<?= $block->getFormAction(); ?>" method="get" id="school-finder__form"
              class="school-finder__form form search">
            <div class="school-finder__wrapper p-4">
                <div class="form-row align-items-center">
                    <input id="school-finder__search" class="school-finder__search py-2 col-10 form-control mr-1"
                           type="search" placeholder="Search by school name, town or any postcode..." minlength="3"
                           maxlength="128" autocomplete="off" name="term"/>
                    <button id="school-finder__submit" type="submit" class="btn btn-secondary col-1 py-2 btn-search btn-round btn-lg">Search
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="results">
    <?php if (!empty($block->getItems())) : ?>
        <?php foreach ($block->getItems() as $school): ?>
            <?php $addresses = [
                $school['address_1'], $school['address_2'], $school['address_3'], $school['town'], $school['postcode']
            ]; ?>
            <a href="<?= $school['url']; ?>" title="<?= $school['school_name'] ?>">
                <?php if (!empty($school['logo'])) : ?>
                    <img src="<?= $school['logo'] ?>" alt="<?= $school['school_name'] ?>">
                <?php endif; ?>
                <h4>
                    <?= $school['school_name']; ?>
                </h4>
                <p>
                    <?php foreach ($addresses as $address) : ?>
                        <?php if (!empty($address)) : ?>
                            <?php if ($address !== end($addresses)) : ?>
                                <?= $address . ", " ?>
                            <?php else: ?>
                                <?= $address ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </p>

            </a>
        <?php endforeach; ?>
    <?php
    endif; ?>
</div>
<script>
    require([
    	'jquery',
        'jquery/ui'
    ], function ( $ ) {

    	var $schoolSearch = $('#school-finder__search'),
            $results = $('.results'),
            cache = {};

	    $schoolSearch.autocomplete({
		    minLength: 3,
		    source: function ( request, response ) {
			    var term = request.term;
			    var isAjax = true;
			    if (term in cache) {
				    response(cache[term]);
				    return;
			    }
			    $.getJSON("<?= $block->getAjaxUrl(); ?>", request, function ( data, status, xhr, isAjax ) {
				    cache[term] = data;
				    response(data);
			    });
		    }
	    });

    });
</script>




