<?php
    /**
     * @package: $Package
     * @company: $Company
     * @author : Luke Paoloni <$Email>
     */

    namespace Kinspeed\Schools\Adapter;

    use \Magento\Framework\Search\RequestInterface;
    use \Mirasvit\SearchElastic\Adapter\ElasticAdapter;

    class SearchAdapter extends ElasticAdapter
    {
        public function query(RequestInterface $request)
        {
            return parent::query($request); // TODO: Change the autogenerated stub
        }

    }